# Generated by Django 3.0.3 on 2020-02-18 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='quiztaker',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_foreign_key',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='quiz_foreign_key',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='questions_count',
            new_name='quiz_difficulty',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='roll_out',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='number_of_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='is_multi_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuizTakers',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
